### ISSUE TITLE
Fix letter spacing on NB International Mono

### ISSUE THREAD

**Issue by mariachristopher** [amcc/gmd2019-gatsby#1]
<img width="213" alt="Screenshot 2019-06-12 at 18 44 46" src="https://user-images.githubusercontent.com/47660004/59373751-32bb3b80-8d42-11e9-9f8e-c2a682e9711f.png">

According to the identity guidelines, tracking on NB International Mono should be -80.

**Comment by amcc** [comment]
fonts are defined in the top Global section of src/utils/styles.js - somewhere around line 82 we could set the body preference

**Comment by mariachristopher** [comment]
Resolved
